apiVersion: sources.knative.dev/v1beta1
kind: KafkaSource
metadata:
  name: iceberg-janitor-kafka
  namespace: iceberg-janitor
  labels:
    app: iceberg-janitor
spec:
  bootstrapServers:
    - kafka:9092
  topics:
    - iceberg-commits
  consumerGroup: iceberg-janitor
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: iceberg-janitor
