apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base
  - minio.yaml
  - kafka.yaml
  - rest-catalog.yaml
  - knative-serving.yaml
  - knative-pingsource.yaml
  - knative-kafkasource.yaml
